#!/usr/bin/env python3
"""Build a stacked all-card benefits report without mutating card-level reports."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


BASE_DIR = Path("/Users/ejazanwar/Documents/Gmail Automations")
OUTPUT = "combined_card_benefits_report.md"


@dataclass(frozen=True)
class ReportLink:
    name: str
    folder: str
    filename: str
    kind: str


CARD_REPORTS = (
    ReportLink("Airtel Axis", "Airtel Axis Statements", "cashback_cap_report.md", "cashback tracker"),
    ReportLink("Flipkart Axis", "Flipkart Axis Statements", "cashback_cap_report.md", "cashback tracker"),
    ReportLink("SBI Cashback", "SBI Cashback Statements", "cashback_cap_report.md", "cashback tracker"),
    ReportLink("HSBC Live+", "HSBC Live Plus Statements", "benefit_tracker_report.md", "benefit tracker"),
    ReportLink("HDFC Diners Black Metal", "HDFC Diners Black Metal Statements", "benefit_tracker_report.md", "benefit tracker"),
    ReportLink("SBI New Card", "SBI New Card Statements", "benefit_tracker_report.md", "benefit tracker"),
)


def _read(path: Path) -> str:
    if not path.exists():
        return f"_Report missing: {path}_\n"
    return path.read_text(encoding="utf-8").strip()


def build_report(base_dir: str | Path = BASE_DIR) -> str:
    base = Path(base_dir)
    lines = [
        "# Combined Card Benefits Tracker",
        "",
        "This combined card benefits report stacks the existing cashback workflows with the new card benefit trackers.",
        "It is a read-only aggregate view: individual card reports are linked and embedded as generated by each card workflow.",
        "",
        "## Card Stack",
        "| Card | Workflow | Report | Status |",
        "| :--- | :--- | :--- | :--- |",
    ]
    for card in CARD_REPORTS:
        path = base / card.folder / card.filename
        status = "Available" if path.exists() else "Missing"
        lines.append(f"| {card.name} | {card.kind} | `{card.folder}/{card.filename}` | {status} |")

    lines.extend(["", "## Stacked Reports", ""])
    for card in CARD_REPORTS:
        path = base / card.folder / card.filename
        lines.extend([f"### {card.name}", "", _read(path), ""])
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    report = build_report(BASE_DIR)
    output = BASE_DIR / OUTPUT
    output.write_text(report, encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
