name: Instamart Hourly Price Tracker

on:
  schedule:
    # Runs automatically at the top of every hour (00:00, 01:00, 02:00 UTC)
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4


      - name: Run Instamart Scraper & Check Price Drops
        working-directory: ./Instamart_Alerts
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          python instamart_scraper.py

      - name: Commit & Push Updated Database
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Instamart_Alerts/instamart_prices.db

          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(auto): update instamart price database snapshot [skip ci]" && git push)

